git checkout master
call .\gradlew build
git checkout 1.19
call .\gradlew build
git checkout 1.19.1
call .\gradlew build
git checkout 1.19.3
call .\gradlew build
git checkout 1.18.1
call .\gradlew build
git checkout 1.17
call .\gradlew build
git checkout 1.16.5
call .\gradlew build
git checkout master